#### Aula 06 - Modelo de Regressão Múltipla

In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
print('Bibliotecas importadas com sucesso!')

Bibliotecas importadas com sucesso!

##### Exercíco 1

In [82]:
# Equação: y = 10 - 1.2 * x1 + 6.8 * x2 + 15.3 * x3 + epsilon (erro)
# y = vendas em uma lanchonete (milhares de $)
# x1 = número de lanchonetes concorrentes no raio de 1 km
# x2 = população no raio de 1 km (milhares de pessoas)
# x3 - uma variável indicadora que vale 1 se a lanchonete tiver drive-thru e 0 se não tiver.

print('a) Qual é o valor médio das vendas quando há 2 lojas concorrentes, 8000 pessoas no raio de 1 km e a lanchonete dispõe de drive-thru?')
vendas_a = 10 - 1.2 * 2 + 6.8 * 8 + 15.3 * 1
print('R: ', vendas_a, 'milhares de $ em vendas\n')

print('b) Qual é o valor médio das vendas quando há 3 lojas concorrentes, 5000 pessoas no raio de 1 km e a lanchonete não dispõe de drive-thru?')
vendas_b = 10 - 1.2 * 3 + 6.8 * 5 + 15.3 * 0
print('R: ', vendas_b, 'milhares de $ em vendas')

a) Qual é o valor médio das vendas quando há 2 lojas concorrentes, 8000 pessoas no raio de 1 km e a lanchonete dispõe de drive-thru?
R:  77.3 milhares de $ em vendas

b) Qual é o valor médio das vendas quando há 3 lojas concorrentes, 5000 pessoas no raio de 1 km e a lanchonete não dispõe de drive-thru?
R:  40.4 milhares de $ em vendas

##### Exercício 2

In [83]:
lstx1 = (2.04, 2.04, 3.06, 3.06, 4.08, 4.08, 2.06, 2.06, 
         3.08, 3.08, 4.11, 4.11, 2.01, 3.02, 4.03)
lstx2 = (3.55, 6.07, 3.55, 6.07, 3.55, 6.16, 3.62, 6.16, 
         3.62, 5.89, 3.62, 5.89, 6.18, 6.18, 6.18)
lstx3= np.multiply(lstx1, lstx2)
lsty= (3.11, 3.26, 3.89, 10.25, 3.11, 13.48, 3.94, 3.53, 
         3.36, 6.49, 2.72, 12.48, 2.82, 5.19, 8.04)
df_ex2 = pd.DataFrame({'x1': lstx1, 'x2': lstx2, 'x3': lstx3, 'y': lsty})
df_ex2

      x1    x2       x3      y
0   2.04  3.55   7.2420   3.11
1   2.04  6.07  12.3828   3.26
2   3.06  3.55  10.8630   3.89
3   3.06  6.07  18.5742  10.25
4   4.08  3.55  14.4840   3.11
5   4.08  6.16  25.1328  13.48
6   2.06  3.62   7.4572   3.94
7   2.06  6.16  12.6896   3.53
8   3.08  3.62  11.1496   3.36
9   3.08  5.89  18.1412   6.49
10  4.11  3.62  14.8782   2.72
11  4.11  5.89  24.2079  12.48
12  2.01  6.18  12.4218   2.82
13  3.02  6.18  18.6636   5.19
14  4.03  6.18  24.9054   8.04

In [84]:
x_pred = sm.add_constant(df_ex2[['x1', 'x2', 'x3']])
y_pred = df_ex2['y']
modelo = sm.OLS(y_pred, x_pred, hasconst=True).fit()
print(modelo.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.825
Model:                            OLS   Adj. R-squared:                  0.778
Method:                 Least Squares   F-statistic:                     17.31
Date:                Wed, 13 Sep 2023   Prob (F-statistic):           0.000178
Time:                        01:52:32   Log-Likelihood:                -27.112
No. Observations:                  15   AIC:                             62.22
Df Residuals:                      11   BIC:                             65.06
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         17.2787      7.167      2.411      0.035       1.505      33.053
x1            -6.3678      2.260     -2.817      0.017     -11.343      -1.393
x2            -3.6584      1.364     -2.682      0.021      -6.660      -0.656
x3             1.7067      0.431      3.956      0.002       0.757       2.656
==============================================================================
Omnibus:                        2.192   Durbin-Watson:                   1.037
Prob(Omnibus):                  0.334   Jarque-Bera (JB):                0.535
Skew:                          -0.320   Prob(JB):                        0.765
Kurtosis:                       3.668   Cond. No.                         302.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

c:\Users\gusta\univesp_disciplinas\.venv\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=15
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [85]:
print('O resultado da regressão é uma reta do tipo:')
print('y = ', modelo.params[0], ' + ', modelo.params[1], ' * x1 + ', modelo.params[2], ' * x2 + ', modelo.params[3], ' * x3\n')
print('Ou arrerondando:')
print('y = ', round(modelo.params[0], 1), '+', round(modelo.params[1], 2), '* x1 +', round(modelo.params[2], 2), '* x2 +', round(modelo.params[3], 2), '* x1*x2\n')

O resultado da regressão é uma reta do tipo:
y =  17.278693889099557  +  -6.36775762379216  * x1 +  -3.658426226863191  * x2 +  1.7067315338624058  * x3

Ou arrerondando:
y =  17.3 + -6.37 * x1 + -3.66 * x2 + 1.71 * x1*x2

In [86]:
# Realizar teste de utilidade do modelo
print('Hipótese Nula (H0): beta_1 = beta_2 = beta_3 = 0')
print('Hipótese Alternativa (H1): pelo menos um beta é diferente de zero\n')

n = len(df_ex2)
print('n =', n)
k = 3
print('k =', k)
gl = n - k - 1
print('gl =', gl)
alpha = 0.05
print('alpha =', alpha)
R_quadrado = modelo.rsquared
print('R_quadrado =', R_quadrado)

# Calculando o valor de F atual
F_atual = (R_quadrado/k)/((1-R_quadrado)/gl)
print('F_atual =', F_atual)

F_crit = stats.f.ppf(q=1-alpha, dfn=k, dfd=gl)
print('F_crit =', F_crit, '\n')

print('Como F_atual é maior que F_crit, rejeitamos a hipótese nula e concluímos que pelo menos um beta é diferente de zero.')

Hipótese Nula (H0): beta_1 = beta_2 = beta_3 = 0
Hipótese Alternativa (H1): pelo menos um beta é diferente de zero

n = 15
k = 3
gl = 11
alpha = 0.05
R_quadrado = 0.8252037753778996
F_atual = 17.3101403244099
F_crit = 3.5874337024204936

Como F_atual é maior que F_crit, rejeitamos a hipótese nula e concluímos que pelo menos um beta é diferente de zero.

In [87]:
# Preditor de interação é o beta_3 porque é ele que está multiplicando x1*x2
# Teste de hipótese para beta_3 para verificar se ele deve ser mantido no modelo ou se deve ser removido
print('Hipótese Nula (H0): beta_3 = 0')
print('Hipótese Alternativa (H1): beta_3 diferente de 0\n')

beta_3 = modelo.params[3]
print('beta_3 =', beta_3)
se_beta_3 = modelo.bse[3]
print('erro_beta_3 =', se_beta_3)
t_atual = beta_3/se_beta_3
print('t_atual =', t_atual)
t_crit = stats.t.ppf(q=1-alpha/2, df=gl)
print('t_crit =', t_crit, '\n')
print('Como t_atual é maior que t_crit, rejietamos a hipótese nula e concluímos que beta_3 é diferente de zero e, portanto, deve ser mantido no modelo.')

Hipótese Nula (H0): beta_3 = 0
Hipótese Alternativa (H1): beta_3 diferente de 0

beta_3 = 1.7067315338624058
erro_beta_3 = 0.4313955435794805
t_atual = 3.956303117322205
t_crit = 2.200985160082949

Como t_atual é maior que t_crit, rejietamos a hipótese nula e concluímos que beta_3 é diferente de zero e, portanto, deve ser mantido no modelo.

In [88]:
# Adicionar modelo quadrático x3 = x1^2, x4 = x2^2 e x5 = x1*x2
lstx3 = np.power(lstx1, 2)
lstx4 = np.power(lstx2, 2)
lstx5 = np.multiply(lstx1, lstx2)
df_ex2_compl = pd.DataFrame({'x1': lstx1, 'x2': lstx2, 'x3': lstx3, 'x4': lstx4, 'x5': lstx5, 'y': lsty})
df_ex2_compl

      x1    x2       x3       x4       x5      y
0   2.04  3.55   4.1616  12.6025   7.2420   3.11
1   2.04  6.07   4.1616  36.8449  12.3828   3.26
2   3.06  3.55   9.3636  12.6025  10.8630   3.89
3   3.06  6.07   9.3636  36.8449  18.5742  10.25
4   4.08  3.55  16.6464  12.6025  14.4840   3.11
5   4.08  6.16  16.6464  37.9456  25.1328  13.48
6   2.06  3.62   4.2436  13.1044   7.4572   3.94
7   2.06  6.16   4.2436  37.9456  12.6896   3.53
8   3.08  3.62   9.4864  13.1044  11.1496   3.36
9   3.08  5.89   9.4864  34.6921  18.1412   6.49
10  4.11  3.62  16.8921  13.1044  14.8782   2.72
11  4.11  5.89  16.8921  34.6921  24.2079  12.48
12  2.01  6.18   4.0401  38.1924  12.4218   2.82
13  3.02  6.18   9.1204  38.1924  18.6636   5.19
14  4.03  6.18  16.2409  38.1924  24.9054   8.04

In [89]:
x_pred = sm.add_constant(df_ex2_compl[['x1', 'x2', 'x3', 'x4', 'x5']])
y_pred = df_ex2_compl['y']
modelo = sm.OLS(y_pred, x_pred, hasconst=True).fit()
print(modelo.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.845
Model:                            OLS   Adj. R-squared:                  0.759
Method:                 Least Squares   F-statistic:                     9.807
Date:                Wed, 13 Sep 2023   Prob (F-statistic):            0.00192
Time:                        01:52:32   Log-Likelihood:                -26.215
No. Observations:                  15   AIC:                             64.43
Df Residuals:                       9   BIC:                             68.68
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -34.3227     48.933     -0.701      0.501    -145.017      76.372
x1            -6.5682      6.364     -1.032      0.329     -20.964       7.827
x2            19.3469     21.662      0.893      0.395     -29.657      68.351
x3             0.0585      0.954      0.061      0.952      -2.100       2.217
x4            -2.3586      2.217     -1.064      0.315      -7.373       2.656
x5             1.6549      0.452      3.661      0.005       0.632       2.677
==============================================================================
Omnibus:                        0.777   Durbin-Watson:                   1.067
Prob(Omnibus):                  0.678   Jarque-Bera (JB):                0.068
Skew:                           0.153   Prob(JB):                        0.967
Kurtosis:                       3.121   Cond. No.                     4.12e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.12e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

c:\Users\gusta\univesp_disciplinas\.venv\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=15
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [90]:
# Verificar se a inclusão de beta_3 e beta_4 é significativa para o modelo
print('Hipótese Nula (H0): beta_3 = beta_4 = 0')
print('Hipótese Alternativa (H1): pelo menos um beta é diferente de zero\n')

n = len(df_ex2_compl)
k = 5
gl = n - k - 1
t_crit = stats.t.ppf(q=1-alpha/2, df=gl)
print('t_crit =', t_crit, '\n')
t_beta_3 = modelo.tvalues[3]
print('t_beta_3 =', t_beta_3)
t_beta_4 = modelo.tvalues[4]
print('t_beta_4 =', t_beta_4, '\n')

print('Como t_beta_3 e t_beta_4 são menores que t_crit, \nnão rejeitamos a hipótese nula e concluímos que beta_3 e beta_4 não são significativos para o modelo.')

Hipótese Nula (H0): beta_3 = beta_4 = 0
Hipótese Alternativa (H1): pelo menos um beta é diferente de zero

t_crit = 2.2621571627409915

t_beta_3 = 0.06128008154635955
t_beta_4 = -1.063990844425219

Como t_beta_3 e t_beta_4 são menores que t_crit,
não rejeitamos a hipótese nula e concluímos que beta_3 e beta_4 não são significativos para o modelo.

##### Exercício 3

![Alt text](Aula06_Ex_03.png)

In [91]:
print('x1 = número de mols de cobalto')
print('x2 = temperatura de calcificação')
print('x3 = x1 * x2')
print('y = Reação de calcificação')

x1 = número de mols de cobalto
x2 = temperatura de calcificação
x3 = x1 * x2
y = Reação de calcificação

In [92]:
lstx1 = (0.6, 0.6, 0.6, 0.6, 0.6, 1.0, 1.0, 1.0, 
         1.0, 1.0, 2.6, 2.6, 2.6, 2.6, 2.6, 2.8, 
         2.8, 2.8, 2.8, 2.8)
lstx2 = (200, 250, 400, 500, 600, 200, 250, 400, 
         500, 600, 200, 250, 400, 500, 600, 200, 
         250, 400, 500, 600)
lstx3= np.multiply(lstx1, lstx2)
lsty= (90.6, 82.7, 58.7, 43.2, 25.0, 127.1, 112.3, 
       19.6, 17.8, 9.1, 53.1, 52.0, 43.4, 42.4, 31.6,
       40.9, 37.9, 27.5, 27.3, 19.0)
df_ex3 = pd.DataFrame({'x1': lstx1, 'x2': lstx2, 'x3': lstx3, 'y': lsty})
df_ex3

     x1   x2      x3      y
0   0.6  200   120.0   90.6
1   0.6  250   150.0   82.7
2   0.6  400   240.0   58.7
3   0.6  500   300.0   43.2
4   0.6  600   360.0   25.0
5   1.0  200   200.0  127.1
6   1.0  250   250.0  112.3
7   1.0  400   400.0   19.6
8   1.0  500   500.0   17.8
9   1.0  600   600.0    9.1
10  2.6  200   520.0   53.1
11  2.6  250   650.0   52.0
12  2.6  400  1040.0   43.4
13  2.6  500  1300.0   42.4
14  2.6  600  1560.0   31.6
15  2.8  200   560.0   40.9
16  2.8  250   700.0   37.9
17  2.8  400  1120.0   27.5
18  2.8  500  1400.0   27.3
19  2.8  600  1680.0   19.0

In [93]:
x_pred_ex3 = sm.add_constant(df_ex3[['x1', 'x2', 'x3']])
y_pred_ex3 = df_ex3['y']
modelo_ex3 = sm.OLS(y_pred_ex3, x_pred_ex3, hasconst=True).fit()
print(modelo_ex3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.780
Model:                            OLS   Adj. R-squared:                  0.739
Method:                 Least Squares   F-statistic:                     18.92
Date:                Wed, 13 Sep 2023   Prob (F-statistic):           1.64e-05
Time:                        01:52:32   Log-Likelihood:                -82.063
No. Observations:                  20   AIC:                             172.1
Df Residuals:                      16   BIC:                             176.1
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        185.4857     21.197      8.750      0.000     140.549     230.422
x1           -45.9695     10.612     -4.332      0.001     -68.466     -23.473
x2            -0.3015      0.051     -5.942      0.000      -0.409      -0.194
x3             0.0888      0.025      3.496      0.003       0.035       0.143
==============================================================================
Omnibus:                        0.894   Durbin-Watson:                   1.182
Prob(Omnibus):                  0.639   Jarque-Bera (JB):                0.082
Skew:                          -0.043   Prob(JB):                        0.960
Kurtosis:                       3.302   Cond. No.                     5.81e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.81e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [94]:
# Calcular uma previsão para x1 = 2.6 e x2 = 250
x1 = 2.6
x2 = 250
y_prev_ex3 = modelo_ex3.predict([1, x1, x2, x1*x2])
print('y_prev_ex3 =', y_prev_ex3)
y_prev_ex3 = modelo_ex3.params[0] + modelo_ex3.params[1] * x1 + modelo_ex3.params[2] * x2 + modelo_ex3.params[3] * x1*x2
print('y_prev_ex3 =', y_prev_ex3, '\n')

# Cálculo do erro da previsão de y
# Pegar valor do dataframe
y_real = df_ex3.loc[(df_ex3['x1'] == x1) & (df_ex3['x2'] == x2)]['y']
print('y_real =', y_real)

residuo = y_real.values[0] - y_prev_ex3
print('\nErro residual =', residuo)

y_prev_ex3 = [48.31030997]
y_prev_ex3 = 48.31030997303422

y_real = 11    52.0
Name: y, dtype: float64

Erro residual = 3.6896900269657777

In [95]:
# Adicionar os resíduos ao dataframe
residuos = modelo_ex3.resid
df_ex3['e'] = residuos
df_ex3

     x1   x2      x3      y          e
0   0.6  200   120.0   90.6 -17.659653
1   0.6  250   150.0   82.7 -13.148551
2   0.6  400   240.0   58.7   0.084754
3   0.6  500   300.0   43.2   9.406958
4   0.6  600   360.0   25.0  16.029161
5   1.0  200   200.0  127.1  30.124023
6   1.0  250   250.0  112.3  25.959097
7   1.0  400   400.0   19.6 -34.835681
8   1.0  500   500.0   17.8 -15.365532
9   1.0  600   600.0    9.1  -2.795384
10  2.6  200   520.0   53.1   1.258726
11  2.6  250   650.0   52.0   3.689690
12  2.6  400  1040.0   43.4   5.682581
13  2.6  500  1300.0   42.4  11.744508
14  2.6  600  1560.0   31.6   8.006435
15  2.8  200   560.0   40.9  -5.299436
16  2.8  250   700.0   37.9  -5.656486
17  2.8  400  1120.0   27.5  -8.127636
18  2.8  500  1400.0   27.3  -3.041737
19  2.8  600  1680.0   19.0  -6.055837

In [96]:
# Verificar se o modelo apresentado é significativo para a explicação da variável resposta
print('Hipótese Nula (H0): beta_1 = beta_2 = beta_3 = 0')
print('Hipótese Alternativa (H1): pelo menos um beta é diferente de zero\n')

n = len(df_ex3)
print('n =', n)
k = 3
print('k =', k)
gl = n - k - 1
print('gl =', gl)

F_atual = (modelo_ex3.rsquared/k)/((1-modelo_ex3.rsquared)/gl)
print('F_atual =', F_atual)

F_crit = stats.f.ppf(q=1-alpha, dfn=k, dfd=gl)
print('F_crit =', F_crit, '\n')

print('Como F_atual é maior que F_crit, rejeitamos a hipótese nula e concluímos que pelo menos um beta é diferente de zero.')

Hipótese Nula (H0): beta_1 = beta_2 = beta_3 = 0
Hipótese Alternativa (H1): pelo menos um beta é diferente de zero

n = 20
k = 3
gl = 16
F_atual = 18.92352857697233
F_crit = 3.238871517453585

Como F_atual é maior que F_crit, rejeitamos a hipótese nula e concluímos que pelo menos um beta é diferente de zero.

In [97]:
# O desvio padrão estimado de S_y_estimado quando o número de mols é 2.0 e a temperatura é 500 é igual a 4,69.
# Calcular o intervalo de confiança de 95% para o valor médio da área de superfície sob essas circunstâncias.
x1 = 2.0
x2 = 500
y_prev_ex3 = modelo_ex3.predict([1, x1, x2, x1*x2])
print('y_prev_ex3 =', y_prev_ex3[0])
previsoes_ex3 = modelo_ex3.get_prediction([1, x1, x2, x1*x2])
S_y_estimado = previsoes_ex3.se_mean[0]
print('S_y_estimado =', S_y_estimado)

# Intervalo de confiança: y_esperada +- t_atual * S_y_estimado
t_atual = stats.t.ppf(q=1-alpha/2, df=gl)
print('t_atual =', t_atual, '\n')

print('Intervalo de confiança =', y_prev_ex3[0], '+-', t_atual * S_y_estimado)
print('Intervalo de confiança = [', y_prev_ex3[0] - t_atual * S_y_estimado, ',', y_prev_ex3[0] + t_atual * S_y_estimado, ']')

y_prev_ex3 = 31.59675707545614
S_y_estimado = 4.694908692270646
t_atual = 2.119905299221011

Intervalo de confiança = 31.59675707545614 +- 9.952761816103328
Intervalo de confiança = [ 21.643995259352813 , 41.549518891559465 ]